const ABSTRACT_BLACK = '#000000';
const ABSTRACT_GLAY = '#999999';

export const COLORS = {
  UI_BASE: ABSTRACT_BLACK,
  UI_TEXT_MAIL: ABSTRACT_BLACK,
  UI_TEXT_SUB: ABSTRACT_GLAY,
  UI_LINE_NORMAL: ABSTRACT_BLACK,
  UI_LINE_WEAKEN: ABSTRACT_GLAY,
  ABSTRACT_BLACK,
} as const;

export default COLORS;
